name: dualdiffusion2 # this env is for blackwell (5000 series) GPUs
channels:            # linux kernel 6.14+, nvidia driver 580+ with CUDA 13.0+ is required
  - nvidia
  - conda-forge
dependencies:
  - python
  - nvidia::cuda-toolkit=13.0.2
  - pip
  - numpy
  - librosa       # faster backend for torchaudio i/o
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/nightly/cu130
    - torch==2.10.0.dev20251011+cu130
    - torchaudio==2.8.0.dev20251011+cu130   # for audio file i/o and spectrogram transforms
    - torchvision==0.25.0.dev20251011+cu130 # required for laion-clap
    - einops        # lightweight lib for cleaner tensor manipulation
    - datasets      # load datasets for training
    - accelerate    # multi-gpu/distributed training
    - safetensors   # fast and safe tensor disk i/o
    - tensorboard   # training logs monitoring web ui
    - opencv-python # image i/o (much faster than PIL)
    - python-dotenv # environment config
    - mutagen       # audio file metadata extraction and editing
    - nicegui       # for interactive web ui
    - transformers  # larger_clap_music
    - laion-clap    # laion-clap (music_audioset_epoch_15_esc_90.14)
    - pyloudnorm    # faster lufs without memory leak
    - pyjson5       # json with comments and some formatting improvements
    - py7zr         # (optional) for dataset unzip util
    - git+https://github.com/KellerJordan/Muon # Muon optimizer for faster training