name: dualdiffusion
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11 # 3.11 for laion-clap, otherwise 3.12
  - nvidia::cudatoolkit
  - pytorch::pytorch
  #- ffmpeg<7::conda-forge # for torchaudio, replaces soundfile
  - pip
  - numpy==1.23.5 # for laion-clap, otherwise *
  - torchaudio
  - torchvision
  - librosa
  - pip:
    - datasets
    - accelerate
    - safetensors
    - tensorboard
    - opencv-python
    - soundfile
    - python-dotenv
    - mutagen
    - nicegui
    - laion-clap
    - py7zr # required for dataset unzip util