name: dualdiffusion
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11   # 3.11 req is for laion-clap, otherwise 3.12+
  - nvidia::cudatoolkit
  - pytorch::pytorch
  - pip
  - numpy==1.23.5 # 1.23.5 req is for laion-clap, otherwise *
  - torchaudio    # for audio file i/o and spectrogram transforms
  - librosa       # faster backend for torchaudio i/o
  - pip:
    - datasets      # load datasets for training
    - accelerate    # multi-gpu/distributed training
    - safetensors   # fast and safe tensor disk i/o
    - tensorboard   # training logs monitoring web ui
    - opencv-python # image i/o
    - python-dotenv # environment config
    - mutagen       # audio file metadata extraction and editing
    - nicegui       # for interactive web ui
    - laion-clap    # CLAP audio/text encoding
    - pyloudnorm    # faster lufs without memory leak
    - pyjson5       # json with comments and some formatting improvements
    - py7zr         # (optional) for dataset unzip util